### ISSUE TITLE
Problem with stripping docker version

### ISSUE THREAD

**Issue by kiendang** [kiendang/aur-nvidia-container-runtime#1]
@jshap70 Same problem as  jshap70/aur-libnvidia-container#4. Currently in aur version of `nvidia-container-runtime` includes docker version `2.0.0+1.docker18.03.0-1`. I would prefer to keep version as `2.0.0` and bump `pkgrel` when updating docker but then if we change now `2.0.0+1.docker18.03.0-1` > `2.0.0`. Might have to change to `2.0.0-docker18.09.3` until the next release.

**Comment by julie-is-late** [comment]
worst case we can always bump the [epoch](https://wiki.archlinux.org/index.php/PKGBUILD#epoch), which will guarantee it to be larger

**Comment by kiendang** [comment]
Yea but using epoch in this case is like solving a temporary problem with a permanent solution.
